[project]
name = "stock-trend-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "akshare>=1.17.98",
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
    "python-dotenv>=1.2.1",
    "seaborn>=0.13.2",
]
